name: .NETCore-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 建立.netcore环境
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: 安装依赖
      run: dotnet restore
    - name: 构建
      run: dotnet build --configuration Release --no-restore
    - name: 添加github仓库
      run: |
        nuget sources add -name github -Source https://nuget.pkg.github.com/wangmaolin-lib/index.json -Username crewml@126.com -Password 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
    - name: 安装nuget 
      uses: nuget/setup-nuget@v1
      with:        
        nuget-version: '5.x'
    - name: 发布生成包到github和nuget
      run: |
        dotnet pack --configuration Release
        nuget push ./bin/Release/*.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate -ApiKey oy2kezdor7zbs3clynrqvwmqtmkd6xuevewnug5t7c26fi -NoSymbol
        nuget push ./bin/Release/*.nupkg -Source github -SkipDuplicate
